### PR TITLE
Add build and install section to README

### PR DESCRIPTION
**Pull request by oliverwiegers**
Add build and install section to README so users know how they can use
the software.

### CODE REVIEW

**Comment by t-8ch** [comment]
I'd like to keep this the meson way.
Do you think it would be much worse just documenting the way to use the meson commands?
If it is fine could you rework the PR to document the meson commands?
Also the builddir should be just `build/` and it should also be added to `.gitignore`

**Comment by t-8ch** [comment]
Thanks for the contribution!

**Comment by oliverwiegers** [comment]
Of course :) Fixed.

**Comment by t-8ch** [comment]
Thanks!

**Pull request merged**
